language: node_js
node_js:
 - "0.10"

sudo: false

services:
 - mongodb

env:
 - CI_SERVER=1

addons:
 code_climate:
    repo_token: 9c90177b42d39905ca635b1f6226580dab5799f87f172b66bab4e8df77b67a13

 apt:
  sources:
    - mongodb-upstart
  packages:
    - mongodb-org
    - mongodb-org-server
    - mongodb-org-shell
    - mongodb-org-tools

before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
  - "mongo --version"
  - gulp build

script:
  - gulp ci

after_script:
 - gulp coverage
 - coveralls < coverage/lcov.info
 - codeclimate < coverage/lcov.info